/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projeksmt2.ui.config;

import java.awt.Color;
import projeksmt2.ui.DashboardForm;
import projeksmt2.util.DBConnection;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.sql.SQLException;
import javax.swing.Timer;

/**
 *
 * @author findo
 */
public class ForgetPassword extends javax.swing.JFrame {

    private String storedAnswerOrEmail = null;
    private boolean usingSecurityQuestion = false;

    /**
     * Creates new form ForgetPassword
     */
    public ForgetPassword() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        question = new javax.swing.JLabel();
        getAnswer = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        newpwText = new javax.swing.JLabel();
        getNewPassword = new javax.swing.JTextField();
        confnewpwText = new javax.swing.JLabel();
        getConfirmPassword = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        getUsername = new javax.swing.JTextField();
        verifyBtn = new javax.swing.JButton();
        confirmBtn = new javax.swing.JButton();
        statusInfo = new javax.swing.JLabel();
        back = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        question.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        question.setText("Question");

        getAnswer.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        jLabel1.setText(" Answer Question Below and create new password");

        newpwText.setFont(new java.awt.Font("Baskerville Old Face", 0, 14)); // NOI18N
        newpwText.setText("New Password:");

        getNewPassword.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        confnewpwText.setFont(new java.awt.Font("Baskerville Old Face", 0, 14)); // NOI18N
        confnewpwText.setText("Confirm New Password:");

        getConfirmPassword.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setFont(new java.awt.Font("SimSun", 0, 14)); // NOI18N
        jLabel2.setText("Enter Username:");

        getUsername.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        getUsername.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        verifyBtn.setText("Verify");
        verifyBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verifyBtnActionPerformed(evt);
            }
        });

        confirmBtn.setText("Confirm");
        confirmBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmBtnActionPerformed(evt);
            }
        });

        statusInfo.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        back.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(back)
                        .addGap(139, 139, 139)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(verifyBtn)
                            .addComponent(jLabel1)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(getConfirmPassword)
                                .addComponent(confnewpwText)
                                .addComponent(getAnswer)
                                .addComponent(getNewPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 322, Short.MAX_VALUE)
                                .addComponent(newpwText)
                                .addComponent(question, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel2)
                            .addComponent(getUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(statusInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(348, 348, 348)
                        .addComponent(confirmBtn)))
                .addContainerGap(304, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(getUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(verifyBtn)
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(question, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(getAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(newpwText, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(getNewPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(confnewpwText, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(getConfirmPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(statusInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(confirmBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // Contoh: Buka form reset password
        new DashboardForm().setVisible(true);

        // Tutup form login jika diperlukan
        this.dispose();
    }//GEN-LAST:event_backActionPerformed

    ///###Verify Button
    private void verifyBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verifyBtnActionPerformed
            String username = getUsername.getText().trim();
            statusInfo.setText("");

            if (username.isEmpty()) {
                statusInfo.setForeground(Color.RED);
                statusInfo.setText("Username tidak boleh kosong.");
                return;
            }

            String sql = "SELECT security_question, security_answer, email FROM users WHERE username = ?";

            try (Connection conn = DBConnection.getConnection(); PreparedStatement pstmt = conn.prepareStatement(sql)) {

                pstmt.setString(1, username);
                ResultSet rs = pstmt.executeQuery();

                if (rs.next()) {
                    String secQuestion = rs.getString("security_question");
                    String secAnswer = rs.getString("security_answer");
                    String email = rs.getString("email");

                    if (secQuestion != null && secAnswer != null) {
                        question.setText(secQuestion);
                        storedAnswerOrEmail = secAnswer;
                        usingSecurityQuestion = true;
                    } else if (email != null) {
                        question.setText("Enter Email Address");
                        storedAnswerOrEmail = email;
                        usingSecurityQuestion = false;
                    } else {
                        statusInfo.setForeground(Color.RED);
                        statusInfo.setText("Tidak ada informasi pemulihan untuk akun ini.");
                        return;
                    }

                    getAnswer.setEditable(true);
                    getNewPassword.setEditable(true);
                    getConfirmPassword.setEditable(true);

                } else {
                    statusInfo.setForeground(Color.RED);
                    statusInfo.setText("Username tidak ditemukan.");
                }

            } catch (SQLException e) {
                e.printStackTrace();
                statusInfo.setForeground(Color.RED);
                statusInfo.setText("Terjadi kesalahan pada database.");
            }
    }//GEN-LAST:event_verifyBtnActionPerformed

    ///###Confirm Button
    private void confirmBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmBtnActionPerformed
            String answerInput = getAnswer.getText().trim();
            String newPassword = getNewPassword.getText().trim();
            String confirmPassword = getConfirmPassword.getText().trim();

            if (answerInput.isEmpty()) {
                statusInfo.setForeground(Color.RED);
                statusInfo.setText("Jawaban atau email harus diisi.");
                return;
            }

            if (!answerInput.equalsIgnoreCase(storedAnswerOrEmail)) {
                statusInfo.setForeground(Color.RED);
                statusInfo.setText(usingSecurityQuestion ? "Jawaban salah." : "Email tidak cocok.");
                return;
            }

            if (newPassword.isEmpty() || confirmPassword.isEmpty()) {
                statusInfo.setForeground(Color.RED);
                statusInfo.setText("Password baru tidak boleh kosong.");
                return;
            }

            if (!newPassword.equals(confirmPassword)) {
                statusInfo.setForeground(Color.RED);
                statusInfo.setText("Password baru dan konfirmasi tidak cocok.");
                return;
            }

            String hashedPassword = hashPassword(newPassword);

            String sql = "UPDATE users SET password = ? WHERE username = ?";
            try (Connection conn = DBConnection.getConnection(); PreparedStatement pstmt = conn.prepareStatement(sql)) {

                pstmt.setString(1, hashedPassword);
                pstmt.setString(2, getUsername.getText().trim());
                int rowsAffected = pstmt.executeUpdate();

                if (rowsAffected > 0) {
                    statusInfo.setForeground(Color.GREEN);
                    statusInfo.setText("Your password successfully changed");

                    // Tambahkan delay agar pesan terlihat sebelum pindah halaman
                    javax.swing.Timer timer = new javax.swing.Timer(2000, (java.awt.event.ActionEvent e) -> {
                        // Tutup form ForgetPassword
                        ForgetPassword.this.dispose();

                        // Buka form DashboardLogin
                        new projeksmt2.ui.DashboardLogin().setVisible(true);
                    });
                    timer.setRepeats(false); // Hanya jalan sekali
                    timer.start();
                } else {
                    statusInfo.setForeground(Color.RED);
                    statusInfo.setText("Gagal mengubah password.");
                }

            } catch (SQLException e) {
                e.printStackTrace();
                statusInfo.setForeground(Color.RED);
                statusInfo.setText("Gagal menyimpan perubahan password.");
            }
    }//GEN-LAST:event_confirmBtnActionPerformed
// 

    //hash
    public static String hashPassword(String password) {
        try {
            MessageDigest digest = MessageDigest.getInstance("SHA-256");
            byte[] hash = digest.digest(password.getBytes(java.nio.charset.StandardCharsets.UTF_8));
            StringBuilder hexString = new StringBuilder();
            for (byte b : hash) {
                String hex = Integer.toHexString(0xff & b);
                if (hex.length() == 1) {
                    hexString.append('0');
                }
                hexString.append(hex);
            }
            return hexString.toString();
        } catch (NoSuchAlgorithmException e) {
            throw new RuntimeException(e);
        }
    }

    ///~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ForgetPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ForgetPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ForgetPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ForgetPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ForgetPassword().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JButton confirmBtn;
    private javax.swing.JLabel confnewpwText;
    private javax.swing.JTextField getAnswer;
    private javax.swing.JTextField getConfirmPassword;
    private javax.swing.JTextField getNewPassword;
    private javax.swing.JTextField getUsername;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel newpwText;
    private javax.swing.JLabel question;
    private javax.swing.JLabel statusInfo;
    private javax.swing.JButton verifyBtn;
    // End of variables declaration//GEN-END:variables
}
