/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projeksmt2.ui;

import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.regex.Pattern; // Untuk validasi email
import projeksmt2.util.DBConnection;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;

/**
 *
 * @author findo
 */
public class DashboardRegister extends javax.swing.JFrame {

    /**
     * Creates new form DashboardRegister
     */
    public DashboardRegister() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        password = new javax.swing.JPasswordField();
        back = new javax.swing.JButton();
        email = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btnRegister = new javax.swing.JButton();
        status = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel1.setText("Register Page");

        username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameActionPerformed(evt);
            }
        });

        jLabel2.setText("Username :");

        jLabel3.setText("Password :");

        password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordActionPerformed(evt);
            }
        });

        back.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailActionPerformed(evt);
            }
        });

        jLabel4.setText("Email:");

        btnRegister.setFont(new java.awt.Font("Yokelvision", 0, 14)); // NOI18N
        btnRegister.setText("Register");
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(back))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(448, 448, 448)
                        .addComponent(btnRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(344, 344, 344)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(username)
                            .addComponent(password, javax.swing.GroupLayout.DEFAULT_SIZE, 287, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(74, 74, 74)
                                .addComponent(jLabel1))
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(email)
                            .addComponent(status, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(349, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(btnRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(status, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameActionPerformed

    private void passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // Tutup window DashboardForm
        this.dispose();

        // Buka window DashboardLogin
        new DashboardForm().setVisible(true);
    }//GEN-LAST:event_backActionPerformed

    private void emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailActionPerformed

    //Button register untuk memastikan semua pengisian sudah benar
    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed

        String usernameStr = username.getText().trim();
        String passwordStr = new String(password.getPassword()).trim();
        String emailStr = email.getText().trim();

        // Reset status
        status.setForeground(Color.RED);
        status.setText("");

        // Validasi input
        if (usernameStr.isEmpty()) {
            status.setText("Username tidak boleh kosong.");
            return;
        }

        if (usernameStr.length() < 3) {
            status.setText("Username minimal 3 karakter.");
            return;
        }

        if (passwordStr.isEmpty()) {
            status.setText("Password tidak boleh kosong.");
            return;
        }

        if (passwordStr.length() < 8) {
            status.setText("Password minimal 8 karakter.");
            return;
        }

        if (!isValidEmail(emailStr)) {
            status.setText("Format email tidak valid.");
            return;
        }

        // Cek duplikasi username dan email di database
        if (isUsernameExists(usernameStr)) {
            status.setText("Username sudah digunakan.");
            return;
        }

        if (isEmailExists(emailStr)) {
            status.setText("Email sudah terdaftar.");
            return;
        }

        if (!isValidUsername(usernameStr)) {
            status.setText("Username hanya boleh berisi huruf dan angka.");
            return;
        }

        //simpan
        if (registerUser(usernameStr, passwordStr, emailStr)) {
            status.setForeground(Color.GREEN);
            status.setText("Register Successfully\nMengarahkan ke halaman Login...");

            // Timer untuk delay 3 detik
            javax.swing.Timer timer = new javax.swing.Timer(3000, e -> {
                // Tutup form Register setelah 3 detik
                this.dispose();

                // Buka DashboardLogin
                new DashboardLogin().setVisible(true);
            });
            timer.setRepeats(false); // Hanya jalan sekali
            timer.start(); // Mulai timer

        } else {
            status.setText("Gagal mendaftarkan akun.");
        }

    }//GEN-LAST:event_btnRegisterActionPerformed
//
//
    //Cek validasi

    private boolean isValidEmail(String email) {
        String emailRegex = "^[a-zA-Z0-9_+&*-]+(?:\\.[a-zA-Z0-9_+&*-]+)*@(?:[a-zA-Z0-9-]+\\.)+[a-zA-Z]{2,7}$";
        return Pattern.matches(emailRegex, email);
    }
    //  

    private boolean isUsernameExists(String username) {
        String sql = "SELECT * FROM users WHERE username = ?";
        try (Connection conn = DBConnection.getConnection(); PreparedStatement pstmt = conn.prepareStatement(sql)) {

            pstmt.setString(1, username);
            ResultSet rs = pstmt.executeQuery();
            return rs.next(); // true jika ada hasil
        } catch (SQLException e) {
            System.out.println("Error cek username: " + e.getMessage());
            return false;
        }
    }

    //
    private boolean isEmailExists(String email) {
        String sql = "SELECT * FROM users WHERE email = ?";
        try (Connection conn = DBConnection.getConnection(); PreparedStatement pstmt = conn.prepareStatement(sql)) {

            pstmt.setString(1, email);
            ResultSet rs = pstmt.executeQuery();
            return rs.next(); // true jika ada hasil
        } catch (SQLException e) {
            System.out.println("Error cek email: " + e.getMessage());
            return false;
        }
    }

    //
    private boolean isIdExists(String id) {
        String sql = "SELECT * FROM users WHERE id = ?";
        try (Connection conn = DBConnection.getConnection(); PreparedStatement pstmt = conn.prepareStatement(sql)) {

            pstmt.setString(1, id);
            ResultSet rs = pstmt.executeQuery();
            return rs.next(); // true jika ID sudah digunakan

        } catch (SQLException e) {
            System.out.println("Error cek ID: " + e.getMessage());
            return true; // asumsi gagal = ID tidak aman untuk dipakai
        }
    }

//function
   private boolean registerUser(String username, String password, String email) {
    Connection conn = null;
    PreparedStatement pstmtUser = null;
    PreparedStatement pstmtEmoney = null;

    try {
        conn = DBConnection.getConnection();
        if (conn == null || conn.isClosed()) {
            status.setText("Koneksi ke database gagal.");
            return false;
        }

        // Generate id user
        String generatedUserId = null;
        int maxAttempts = 100;
        for (int i = 0; i < maxAttempts; i++) {
            generatedUserId = generateRandomUserId(); // "ur" + 8 digit
            if (!isIdExists(generatedUserId)) {
                break;
            }
            if (i == maxAttempts - 1) {
                status.setText("Gagal menghasilkan ID pengguna unik.");
                return false;
            }
        }

        // Insert user
        String sqlUser = "INSERT INTO users(id, username, password, email, role) VALUES (?, ?, ?, ?, 'user')";
        pstmtUser = conn.prepareStatement(sqlUser);
        pstmtUser.setString(1, generatedUserId);
        pstmtUser.setString(2, username);
        pstmtUser.setString(3, DashboardRegister.hashPassword(password));
        pstmtUser.setString(4, email);

        int affectedRowsUser = pstmtUser.executeUpdate();
        if (affectedRowsUser <= 0) {
            return false;
        }

        // Generate emoney_id unik
        String generatedEmoneyId = null;
        for (int i = 0; i < maxAttempts; i++) {
            generatedEmoneyId = generateRandomEmoneyId(); // "em" + 5 digit
            if (!isEmoneyIdExists(generatedEmoneyId)) {
                break;
            }
            if (i == maxAttempts - 1) {
                status.setText("Gagal menghasilkan emoney_id unik.");
                return false;
            }
        }

        // Insert emoney
        String sqlEmoney = "INSERT INTO emoney(emoney_id, balance, coin, topup_status, user_id) VALUES (?, 0, 0, 'idle', ?)";
        pstmtEmoney = conn.prepareStatement(sqlEmoney);
        pstmtEmoney.setString(1, generatedEmoneyId);
        pstmtEmoney.setString(2, generatedUserId);

        int affectedRowsEmoney = pstmtEmoney.executeUpdate();
        return affectedRowsEmoney > 0;

    } catch (SQLException e) {
        System.out.println("Error saat registrasi: " + e.getMessage());
        status.setText("Gagal mendaftarkan akun: " + e.getMessage());
        return false;
    } finally {
        try {
            if (pstmtEmoney != null) pstmtEmoney.close();
            if (pstmtUser != null) pstmtUser.close();
            if (conn != null) conn.close();
        } catch (SQLException e) {
            System.out.println("Error menutup koneksi: " + e.getMessage());
        }
    }
}

//
private String generateRandomUserId() {
    StringBuilder sb = new StringBuilder("ur");
    java.util.Random random = new java.util.Random();
    for (int i = 0; i < 8; i++) {
        sb.append(random.nextInt(10)); // tambahkan angka acak 0-9
    }
    return sb.toString();
}

private String generateRandomEmoneyId() {
    StringBuilder sb = new StringBuilder("em");
    java.util.Random random = new java.util.Random();
    for (int i = 0; i < 5; i++) {
        sb.append(random.nextInt(10)); // tambahkan angka acak 0-9
    }
    return sb.toString();
}

private boolean isEmoneyIdExists(String emoneyId) {
    String sql = "SELECT * FROM emoney WHERE emoney_id = ?";
    try (Connection conn = DBConnection.getConnection(); 
         PreparedStatement pstmt = conn.prepareStatement(sql)) {
        pstmt.setString(1, emoneyId);
        ResultSet rs = pstmt.executeQuery();
        return rs.next(); // true jika sudah digunakan
    } catch (SQLException e) {
        System.out.println("Error cek emoney_id: " + e.getMessage());
        return true; // asumsi gagal = ID tidak aman
    }
}

    ///
  private boolean isValidUsername(String username) {
        return username != null && username.matches("[a-zA-Z0-9]{3,50}");
    }

    ///
    
// Method untuk hash password menggunakan SHA-256
    public static String hashPassword(String password) {
        try {
            MessageDigest digest = MessageDigest.getInstance("SHA-256");
            byte[] hash = digest.digest(password.getBytes(java.nio.charset.StandardCharsets.UTF_8));
            StringBuilder hexString = new StringBuilder();

            for (byte b : hash) {
                String hex = Integer.toHexString(0xff & b);
                if (hex.length() == 1) {
                    hexString.append('0');
                }
                hexString.append(hex);
            }

            return hexString.toString();
        } catch (NoSuchAlgorithmException e) {
            throw new RuntimeException(e);
        }
    }

    //////////////////////-w-
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DashboardRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DashboardRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DashboardRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DashboardRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DashboardRegister().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JButton btnRegister;
    private javax.swing.JTextField email;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPasswordField password;
    private javax.swing.JLabel status;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
