package projeksmt2.ui;

import projeksmt2.ui.config.ForgetPassword;
import java.awt.Color;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import projeksmt2.util.DBConnection;
import projeksmt2.util.SessionManager;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author findo
 */
public class DashboardLogin extends javax.swing.JFrame {

    /**
     * Creates new form DashboardLogin
     */
    public DashboardLogin() {
        initComponents();
        // Set cursor menjadi hand cursor
        forget.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        // Mouse Listener untuk efek hover dan klik
        forget.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                forget.setForeground(java.awt.Color.RED); // Warna saat dihover
            }

            @Override
            public void mouseExited(java.awt.event.MouseEvent evt) {
                forget.setForeground(java.awt.Color.BLUE); // Warna default
            }

            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                // Aksi ketika diklik
                handleForgetPassword();
            }
        });

        //~~~
        // Set cursor untuk register label
        register.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

// Tambahkan MouseListener untuk klik pada register
        register.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                // Tutup form login dan buka DashboardRegister
                new DashboardRegister().setVisible(true);
                DashboardLogin.this.dispose(); // Tutup form saat ini
            }

            @Override
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                register.setForeground(java.awt.Color.RED); // Ubah warna saat dihover
            }

            @Override
            public void mouseExited(java.awt.event.MouseEvent evt) {
                register.setForeground(java.awt.Color.BLACK); // Kembali ke warna asli
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        password = new javax.swing.JPasswordField();
        back = new javax.swing.JButton();
        btnLogin = new javax.swing.JButton();
        status = new javax.swing.JLabel();
        forget = new javax.swing.JLabel();
        register = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel1.setText("Login Page");

        username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameActionPerformed(evt);
            }
        });

        jLabel2.setText("Username :");

        jLabel3.setText("Password :");

        password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordActionPerformed(evt);
            }
        });

        back.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        btnLogin.setFont(new java.awt.Font("Yokelvision", 0, 14)); // NOI18N
        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        forget.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        forget.setText("Forget Password?");

        register.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        register.setText("Don't have account? Register here");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(344, 344, 344)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(74, 74, 74)
                                .addComponent(jLabel1))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(username)
                                .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(status, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(102, 102, 102)
                                .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(back))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(436, 436, 436)
                        .addComponent(forget))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(register, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13)))
                .addContainerGap(349, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(forget)
                .addGap(3, 3, 3)
                .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(status, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(register)
                .addContainerGap(74, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordActionPerformed

    private void usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // Tutup window DashboardForm
        this.dispose();

        // Buka window DashboardLogin
        new DashboardForm().setVisible(true);
    }//GEN-LAST:event_backActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed

    String usernameStr = username.getText().trim();
    String passwordStr = new String(password.getPassword()).trim();

    // Reset status
    status.setForeground(Color.RED);
    status.setText("");

    // Validasi input kosong
    if (usernameStr.isEmpty()) {
        status.setText("Username tidak boleh kosong.");
        return;
    }

    if (passwordStr.isEmpty()) {
        status.setText("Password tidak boleh kosong.");
        return;
    }

    // Cek kredensial dan ambil role dari database
    String[] userData = validateAndGetRole(usernameStr, passwordStr);
    if (userData != null) {
        if ("terminated".equals(userData[0])) {
            // Tampilkan pesan error karena akun ditutup
            status.setForeground(Color.RED);
            status.setText("Your account has been terminated.");
            return; // Hentikan proses login
        }

        String role = userData[1];
        String userId = userData[2]; // Ambil user id yang dikembalikan

        // Simpan sesi pengguna
        SessionManager.login(usernameStr, role, userId); // Menyimpan userId
        status.setForeground(Color.GREEN);
        status.setText("Login Successfully");

        // Tutup form setelah delay 3 detik dan arahkan ke dashboard sesuai role
        javax.swing.Timer timer = new javax.swing.Timer(3000, e -> {
            this.dispose(); // Tutup form Login

             // Arahkan ke dashboard sesuai dengan role
            if ("user".equalsIgnoreCase(role)) {
                new DashboardUser().setVisible(true); // Arahkan ke DashboardUser
            } else if ("admin".equalsIgnoreCase(role)) {
                new DashboardAdmin().setVisible(true); // Arahkan ke DashboardAdmin
            } else if ("warehouse_manager".equalsIgnoreCase(role)) {
                new DashboardWarehouse().setVisible(true); // Arahkan ke DashboardWarehouse
            } else if ("outlet_manager".equalsIgnoreCase(role)) {
                new DashboardOutlet().setVisible(true); // Arahkan ke DashboardOutlet
            }
        });
        timer.setRepeats(false);
        timer.start();

    } else {
        status.setText("Username atau Password salah.");
    }

    }//GEN-LAST:event_btnLoginActionPerformed
//
    //validate credentials

// Method untuk validasi kredensial sekaligus mengambil role
private String[] validateAndGetRole(String username, String password) {
    String sql = "SELECT * FROM users WHERE username = ? AND password = ?";
    try (Connection conn = DBConnection.getConnection(); PreparedStatement pstmt = conn.prepareStatement(sql)) {

        pstmt.setString(1, username);
        pstmt.setString(2, DashboardLogin.hashPassword(password));
        ResultSet rs = pstmt.executeQuery();

        if (rs.next()) {
            // Cek apakah akun ditutup (terminated_reason tidak kosong)
            String terminatedReason = rs.getString("terminated_reason");
            if (terminatedReason != null && !terminatedReason.isEmpty()) {
                // Akun ditutup
                return new String[]{"terminated", null, null}; // Tandai sebagai akun yang ditutup
            }

            String userRole = rs.getString("role");
            String userId = rs.getString("id"); // Ambil user id
            return new String[]{rs.getString("username"), userRole, userId}; // [username, role, userId]
        }
    } catch (SQLException e) {
        System.out.println("Error saat validasi kredensial: " + e.getMessage());
    }
    return null;
}

    // Method untuk hash password menggunakan SHA-256
    public static String hashPassword(String password) {
        try {
            MessageDigest digest = MessageDigest.getInstance("SHA-256");
            byte[] hash = digest.digest(password.getBytes(java.nio.charset.StandardCharsets.UTF_8));
            StringBuilder hexString = new StringBuilder();

            for (byte b : hash) {
                String hex = Integer.toHexString(0xff & b);
                if (hex.length() == 1) {
                    hexString.append('0');
                }
                hexString.append(hex);
            }

            return hexString.toString();
        } catch (NoSuchAlgorithmException e) {
            throw new RuntimeException(e);
        }
    }

    private void handleForgetPassword() {
        // Contoh: Buka form reset password
        new ForgetPassword().setVisible(true);

        // Tutup form login jika diperlukan
        this.dispose();
    }

    //////////////////// -w-
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DashboardLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DashboardLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DashboardLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DashboardLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DashboardLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JButton btnLogin;
    private javax.swing.JLabel forget;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPasswordField password;
    private javax.swing.JLabel register;
    private javax.swing.JLabel status;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
